#### Nexys4 Board ####
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]
################################################################################
## Clock & Reset
# Clock
    set_property PACKAGE_PIN E3 [get_ports clk_100mhz]
    set_property IOSTANDARD LVCMOS33 [get_ports clk_100mhz]
    create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports clk_100mhz]
# Reset Button
    set_property PACKAGE_PIN C12 [get_ports cpu_reset]
    set_property IOSTANDARD LVCMOS33 [get_ports cpu_reset]
################################################################################
## Green LEDs
    set_property PACKAGE_PIN T8 [get_ports {led[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
    set_property PACKAGE_PIN V9 [get_ports {led[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
    set_property PACKAGE_PIN R8 [get_ports {led[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
    set_property PACKAGE_PIN T6 [get_ports {led[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
    set_property PACKAGE_PIN T5 [get_ports {led[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
    set_property PACKAGE_PIN T4 [get_ports {led[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
    set_property PACKAGE_PIN U7 [get_ports {led[6]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
    set_property PACKAGE_PIN U6 [get_ports {led[7]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}]
    set_property PACKAGE_PIN V4 [get_ports {led[8]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {led[8]}]
    set_property PACKAGE_PIN U3 [get_ports {led[9]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {led[9]}]
    set_property PACKAGE_PIN V1 [get_ports {led[10]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {led[10]}]
    set_property PACKAGE_PIN R1 [get_ports {led[11]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {led[11]}]
    set_property PACKAGE_PIN P5 [get_ports {led[12]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {led[12]}]
    set_property PACKAGE_PIN U1 [get_ports {led[13]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {led[13]}]
    set_property PACKAGE_PIN R2 [get_ports {led[14]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {led[14]}]
    set_property PACKAGE_PIN P2 [get_ports {led[15]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {led[15]}]
################################################################################
## Display
    #set_property PACKAGE_PIN L3 [get_ports DISP_CA]
    #set_property IOSTANDARD LVCMOS33 [get_ports DISP_CA]
    #set_property PACKAGE_PIN N1 [get_ports DISP_CB]
    #set_property IOSTANDARD LVCMOS33 [get_ports DISP_CB]
    #set_property PACKAGE_PIN L5 [get_ports DISP_CC]
    #set_property IOSTANDARD LVCMOS33 [get_ports DISP_CC]
    #set_property PACKAGE_PIN L4 [get_ports DISP_CD]
    #set_property IOSTANDARD LVCMOS33 [get_ports DISP_CD]
    #set_property PACKAGE_PIN K3 [get_ports DISP_CE]
    #set_property IOSTANDARD LVCMOS33 [get_ports DISP_CE]
    #set_property PACKAGE_PIN M2 [get_ports DISP_CF]
    #set_property IOSTANDARD LVCMOS33 [get_ports DISP_CF]
    #set_property PACKAGE_PIN L6 [get_ports DISP_CG]
    #set_property IOSTANDARD LVCMOS33 [get_ports DISP_CG]
    #set_property PACKAGE_PIN M4 [get_ports DISP_DP]
    #set_property IOSTANDARD LVCMOS33 [get_ports DISP_DP]
    #set_property PACKAGE_PIN N6 [get_ports {DISP_AN[0]}]
    #set_property IOSTANDARD LVCMOS33 [get_ports {DISP_AN[0]}]
    #set_property PACKAGE_PIN M6 [get_ports {DISP_AN[1]}]
    #set_property IOSTANDARD LVCMOS33 [get_ports {DISP_AN[1]}]
    #set_property PACKAGE_PIN M3 [get_ports {DISP_AN[2]}]
    #set_property IOSTANDARD LVCMOS33 [get_ports {DISP_AN[2]}]
    #set_property PACKAGE_PIN N5 [get_ports {DISP_AN[3]}]
    #set_property IOSTANDARD LVCMOS33 [get_ports {DISP_AN[3]}]
    #set_property PACKAGE_PIN N2 [get_ports {DISP_AN[4]}]
    #set_property IOSTANDARD LVCMOS33 [get_ports {DISP_AN[4]}]
    #set_property PACKAGE_PIN N4 [get_ports {DISP_AN[5]}]
    #set_property IOSTANDARD LVCMOS33 [get_ports {DISP_AN[5]}]
    #set_property PACKAGE_PIN L1 [get_ports {DISP_AN[6]}]
    #set_property IOSTANDARD LVCMOS33 [get_ports {DISP_AN[6]}]
    #set_property PACKAGE_PIN M1 [get_ports {DISP_AN[7]}]
    #set_property IOSTANDARD LVCMOS33 [get_ports {DISP_AN[7]}]
################################################################################
## Slide Switches
    set_property PACKAGE_PIN U9 [get_ports {sw[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {sw[0]}]
    set_property PACKAGE_PIN U8 [get_ports {sw[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {sw[1]}]
    set_property PACKAGE_PIN R7 [get_ports {sw[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {sw[2]}]
    set_property PACKAGE_PIN R6 [get_ports {sw[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {sw[3]}]
    set_property PACKAGE_PIN R5 [get_ports {sw[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {sw[4]}]
    set_property PACKAGE_PIN V7 [get_ports {sw[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {sw[5]}]
    set_property PACKAGE_PIN V6 [get_ports {sw[6]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {sw[6]}]
    set_property PACKAGE_PIN V5 [get_ports {sw[7]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {sw[7]}]
    set_property PACKAGE_PIN U4 [get_ports {sw[8]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {sw[8]}]
    set_property PACKAGE_PIN V2 [get_ports {sw[9]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {sw[9]}]
    set_property PACKAGE_PIN U2 [get_ports {sw[10]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {sw[10]}]
    set_property PACKAGE_PIN T3 [get_ports {sw[11]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {sw[11]}]
    set_property PACKAGE_PIN T1 [get_ports {sw[12]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {sw[12]}]
    set_property PACKAGE_PIN R3 [get_ports {sw[13]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {sw[13]}]
    set_property PACKAGE_PIN P3 [get_ports {sw[14]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {sw[14]}]
    set_property PACKAGE_PIN P4 [get_ports {sw[15]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {sw[15]}]
################################################################################
## Buttons
    #set_property PACKAGE_PIN E16 [get_ports BTN_C]                      
    #set_property IOSTANDARD LVCMOS33 [get_ports BTN_C]
    #set_property PACKAGE_PIN F15 [get_ports BTN_U]                      
    #set_property IOSTANDARD LVCMOS33 [get_ports BTN_U]
    #set_property PACKAGE_PIN T16 [get_ports BTN_L]                      
    #set_property IOSTANDARD LVCMOS33 [get_ports BTN_L]
    #set_property PACKAGE_PIN R10 [get_ports BTN_R]                      
    #set_property IOSTANDARD LVCMOS33 [get_ports BTN_R]
    #set_property PACKAGE_PIN V10 [get_ports BTN_D]                      
    #set_property IOSTANDARD LVCMOS33 [get_ports BTN_D]
################################################################################
## USB-RS232 Interface
    set_property PACKAGE_PIN C4 [get_ports uart_txd]
    set_property IOSTANDARD LVCMOS33 [get_ports uart_txd]
    set_property PACKAGE_PIN D4 [get_ports uart_rxd]
    set_property IOSTANDARD LVCMOS33 [get_ports uart_rxd]
    set_property PACKAGE_PIN D3 [get_ports uart_cts]
    set_property IOSTANDARD LVCMOS33 [get_ports uart_cts]
    set_property PACKAGE_PIN E5 [get_ports uart_rts]
    set_property IOSTANDARD LVCMOS33 [get_ports uart_rts]
################################################################################
## Ethernet PHY
	#set_property PACKAGE_PIN C9 [get_ports ETH_MDC]						
	#set_property IOSTANDARD LVCMOS33 [get_ports ETH_MDC]
	#set_property PACKAGE_PIN A9 [get_ports ETH_MDIO]					
	#set_property IOSTANDARD LVCMOS33 [get_ports ETH_MDIO]
	#set_property PACKAGE_PIN B3 [get_ports ETH_NRESET]					
	#set_property IOSTANDARD LVCMOS33 [get_ports ETH_NRESET]
	#set_property PACKAGE_PIN D9 [get_ports ETH_CRS_DV]						
	#set_property IOSTANDARD LVCMOS33 [get_ports ETH_CRS_DV]
	#set_property PACKAGE_PIN C10 [get_ports ETH_RXERR]					
	#set_property IOSTANDARD LVCMOS33 [get_ports ETH_RXERR]
	#set_property PACKAGE_PIN D10 [get_ports {ETH_RXD[0]}]				
	#set_property IOSTANDARD LVCMOS33 [get_ports {ETH_RXD[0]}]
	#set_property PACKAGE_PIN C11 [get_ports {ETH_RXD[1]}]				
	#set_property IOSTANDARD LVCMOS33 [get_ports {ETH_RXD[1]}]
	#set_property PACKAGE_PIN B9 [get_ports ETH_TXEN]					
	#set_property IOSTANDARD LVCMOS33 [get_ports ETH_TXEN]
	#set_property PACKAGE_PIN A10 [get_ports {ETH_TXD[0]}]				
	#set_property IOSTANDARD LVCMOS33 [get_ports {ETH_TXD[0]}]
	#set_property PACKAGE_PIN A8 [get_ports {ETH_TXD[1]}]				
	#set_property IOSTANDARD LVCMOS33 [get_ports {ETH_TXD[1]}]
	#set_property PACKAGE_PIN D5 [get_ports ETH_CLK]				
	#set_property IOSTANDARD LVCMOS33 [get_ports ETH_CLK]
	#set_property PACKAGE_PIN B8 [get_ports ETH_NINT]					
	#set_property IOSTANDARD LVCMOS33 [get_ports ETH_NINT]
################################################################################